[project]
name = "OpenStudioLandscapes-OpenCue"
description = "OpenCue Feature for OpenStudioLandscapes"

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-OpenCue"

[project.optional-dependencies]
sbom = [
    "OpenStudioLandscapes-OpenCue[graphviz]",
]
nox = [
    "OpenStudioLandscapes-OpenCue[testing]",
]
dev = [
    "OpenStudioLandscapes-OpenCue[testing]",
    "OpenStudioLandscapes-OpenCue[lint]",
    "OpenStudioLandscapes-OpenCue[nox]",
    "OpenStudioLandscapes-OpenCue[sbom]",
    "OpenStudioLandscapes-OpenCue[coverage]",
    "OpenStudioLandscapes-OpenCue[readme]",
]

[tool.setuptools]
packages = [
    "OpenStudioLandscapes.OpenCue"
]

[tool.dagster]
module_name = "OpenStudioLandscapes.OpenCue.definitions"
code_location_name = "OpenStudioLandscapes-OpenCue"
